language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

install:
  - "npm install"

# Run mocha with more flexible timeouts and omit the {start|stop}_managed.js tests
script: ./node_modules/.bin/mocha --timeout 10000 --invert --grep "#*_managed.js"